### ISSUE TITLE
Firefox, Board of Trustees & Team: Bio headshots overlap text

### ISSUE THREAD

**Issue by francescagenello** [VitalDevTeam/Center-for-Medical-Simulation#287]
http://cms.dev.madebyvital.com/about/cms-team/
http://cms.dev.madebyvital.com/about/board-of-trustees/

The bio headshots overlap with the bio text.

<img width="824" alt="screen shot 2017-04-27 at 11 55 04 am" src="https://cloud.githubusercontent.com/assets/18056150/25492294/9ebf751e-2b40-11e7-9e43-480844d5d5a1.png">

**Comment by lmajerus** [comment]
IE11 - the text overlaps the headshot. This problem does not exist in Chrome, Firefox, or Edge: only in Internet Explorer.

![image](https://user-images.githubusercontent.com/22547623/27404486-3d25eb8a-569c-11e7-9d6e-23f2c0942443.png)

**Comment by mavedisian** [comment]
Hi @lmajerus, this has been fixed and pushed to production.
