### ISSUE TITLE
Form Confirmation Message 

### ISSUE THREAD

**Issue by JuliaAhumada** [VitalDevTeam/Center-for-Medical-Simulation#322]
Each form type should display a different confirmation message.

***Simulation Instructor Training Form:***

APPLICATION SUBMITTED

Thank you for applying to one of our Simulation Instructor Training courses offered through the Institute for Medical Simulation (IMS). Your application has been submitted with a copy sent to the email address you provided on the application form. If you do NOT receive a confirmation email message within 1 hour of submitting your application, please contact us at info@harvardmedsim.org.

You should expect to receive a reply from us within 5 business days.

_______________________________________________________________________________________________________

***MOCA/Crisis Resource Management Training for Practicing Anesthesiologists (ACRM) Form:***

APPLICATION SUBMITTED

Thank you for applying to attend a MOCA®/Crisis Resource Management Training for Practicing Anesthesiologists (ACRM) course at the Center for Medical Simulation. Your application has been submitted with a copy sent to the email address you provided on the application form. If you do NOT receive a confirmation email message within 1 hour of submitting your application, please contact us at info@harvardmedsim.org.

You should expect to receive a reply from us within 5 business days.

________________________________________________________________________________________________________

***Labor and Delivery Team Form:***

APPLICATION SUBMITTED

Thank you for applying to attend a Crisis Resource Management (CRM) Clinical Training course for Labor and Delivery Clinicians at the Center for Medical Simulation. Your application has been submitted with a copy sent to the email address you provided on the application form. If you do NOT receive a confirmation email message within 1 hour of submitting your application, please contact us at info@harvardmedsim.org. 

You should expect to receive a reply from us within 5 business days.

**Comment by mavedisian** [comment]
Hi @lmajerus These are fixed on production, but may need some additional tweaking depending on how CMS would like these configured. I noticed there are a couple of courses that don't display a custom confirmation on submission, but I am unsure of which courses are matched to which confirmations. 

They are to be set up the same way conditional logic for notifications are set up. If there are further issues in testing/setting these up, let me know.

**Comment by mavedisian** [comment]
@lmajerus Could you please review so we can potentially close this? Thank you.

**Comment by lmajerus** [comment]
These were all done. I updated the conditional logic and email addresses to each specific Confirmation page. These Confirmation will be replaced with course thank you pages in the near future.
