### ISSUE TITLE
Missing Blog Posts from old site

### ISSUE THREAD

**Issue by lmajerus** [VitalDevTeam/Center-for-Medical-Simulation#331]
We've realized that some blog posts from our old site were not transferred to the new site. If it's not possible to migrate them, we're willing to copy/paste/repost them (hopefully, it's only a handful) - specifically February (may be nothing) and April 2017 seem to be missing as well as the Media files from those posts.

Is there a way to access the old WP site to access that content?

I have a backup of all the files from the php part of the old site but not the last copy of the old WP site to be able to install on a separate server.... I've tried to access the old site via both cPanel and FTP but cannot gain access.

**Comment by lmajerus** [comment]
> Good catch with the https://cms.dev.madebyvital.com/wp-content/uploads/ references... those are a result of a missed search and replace. I have done another search/replace on production to correct those wrong URLs.

This is great news. Why are the old media files not appearing in the Media Library though? I'm certain some (though definitely not all) would be useful to reuse. Is there a way to access the files via FTP?

> As for missing images from old blog posts, if the images are missing on our archived site (@ http://74.50.27.234/) there's not much I can do unless we have another backup with those media files available to recover.

I've been able to find the missing images from the old blog posts and extract them from the archived site. I'm working on putting them back into those posts.

**Comment by lmajerus** [comment]
Hmm, wondering if another find/replace is needed to get the images to appear in the Media Library. Looking at some old blog posts, I see the media files are going to https://harvardmedsim.org/news/wp-content/uploads/ while adding a new image, the root is https://harvardmedsim.org/wp-content/uploads/.

Could you make this change on production?
OLD: https://harvardmedsim.org/news/wp-content/uploads/
CHANGE TO: https://harvardmedsim.org/wp-content/uploads/

**Comment by lmajerus** [comment]
Hi @mavedisian , we're still missing 3 posts from the old site:

- Published 2016/09/29 11:34:21 am by James Lipshaw
Crisis Management in Acute Care Settings Available November 2016

- Published 2016/09/22 1:41:46 pm by James Lipshaw
Janice Palaganas to Deliver Debra Spunt Lecture at NLN Education Summit

- Published 2016/08/25 1:17:52 pm by Gary Rossi
Center for Medical Simulation Offers Nurse Educator Scholarships

Can you please bring these 3 posts over? I have the media files already, just need the posts to update on the new site. Thanks!

**Comment by mavedisian** [comment]
@lmajerus These are now imported.

**Comment by lmajerus** [comment]
Hi @mavedisian I'm wondering if another find/replace is needed to get the images to appear in the Media Library. Looking at some old blog posts, I see the media files are going to https://harvardmedsim.org/news/wp-content/uploads/ while adding a new image, the root is https://harvardmedsim.org/wp-content/uploads/.

Could you make this change on production?
OLD: https://harvardmedsim.org/news/wp-content/uploads/
CHANGE TO: https://harvardmedsim.org/wp-content/uploads/

**Comment by lmajerus** [comment]
Hi @mavedisian. Why are the old media files not appearing in the Media Library though? I'm certain some (though definitely not all) would be useful to reuse. Is there a way to access the files via FTP?

**Comment by mavedisian** [comment]
Hi @lmajerus, the find/replace is complete. 

You can access the files via FTP by visiting the web site root, and looking in wp-content/uploads/ files are stored by month.

**Comment by lmajerus** [comment]
Hi @mavedisian. I don't have any info on how to FTP for the new site.

- What's the address for FTP?
- Is there a specific login/password or will my WP credentials work?

**Comment by lmajerus** [comment]
Thanks @mavedisian. I'm closing this ticket again and opening a different one to request FTP access.
