### ISSUE TITLE
Single Large Video: Create top spacing when used as 1st element on page

### ISSUE THREAD

**Issue by lmajerus** [VitalDevTeam/Center-for-Medical-Simulation#348]
Add top padding to id="single-large-video" element so that if the element is the 1st widget on the page, there's spacing between the hero and video element. Right now, they are adjacent and it looks weird.
See: https://harvardmedsim.org/about/
![screen shot 2017-05-16 at 3 23 05 pm](https://cloud.githubusercontent.com/assets/22547623/26124197/9ebcbd32-3a4b-11e7-8347-36e7c0137457.png)

**Comment by lmajerus** [comment]
Hi @mavedisian - I forgot to send you the approval for this. The spacing change is approved. Please push to production.

**Comment by mavedisian** [comment]
It has been pushed.
