### ISSUE TITLE
Events: How to export as .csv?

### ISSUE THREAD

**Issue by lmajerus** [VitalDevTeam/Center-for-Medical-Simulation#352]
On the back-end, I assumed I could do Bulk Actions, Export Entries for Events - just like Form entries. This assumption turns out to be false. I'm looking for a way to export Events with dates - ideally with selectable date range and category but that's not critical. Is there a way to do this directly from WP without having to access the MySQL db?

**Comment by JuliaAhumada** [comment]
Yes, we buy it and pass the cost along with a small markup.

**Comment by lmajerus** [comment]
@JuliaAhumada Please purchase the WP All Export plugin. Thanks

**Comment by mavedisian** [comment]
Pro version purchased and installed on Production.
