### ISSUE TITLE
Visit: Anchors to allow quick links for Getting To CMS section

### ISSUE THREAD

**Issue by lmajerus** [VitalDevTeam/Center-for-Medical-Simulation#354]
On our old site, we had anchors that allowed people to skip to specific relevant sections of the Directions to CMS page. On the new site, the functionality is clean and smooth but I cannot figure out how I could link someone directly to say "Partners Healthcare Shuttles" or one of the specific shuttle options that appear in the accordion.
Example of how we did it on the old site:
Automobile: https://harvardmedsim.org/pop-directions-automobile.php
From the NORTH via I-93 SOUTH: https://harvardmedsim.org/pop-directions-automobile.php#FromNorth93
From the NORTH via ROUTE 1 SOUTH: https://harvardmedsim.org/pop-directions-automobile.php#FromNorth1

I'm not asking for new functionality on our new site. I'm only wondering if it is possible with the existing set-up to be able to create links that go to the specific sections like you have for the Board of Trustees and CMS Team pages where you can skip to different sections of the page.

**Comment by mavedisian** [comment]
Hi @lmajerus, I'm sorry, but no there is no way to currently link to a accordion section and have it automatically open up. It was not spec'ed or dev'ed with that in mind.
