### ISSUE TITLE
Interior Hero text: Change heading styling for Calendar pages

### ISSUE THREAD

**Issue by lmajerus** [VitalDevTeam/Center-for-Medical-Simulation#356]
Hi @mavedisian. The hero font weight for the Calendar pages (both Month/List/Day view and Event Details)  do not match the same text as other interior page heros. All the full-color and full-image heros have a h1.heading-test font weight of 300 while the Calendar headings are font weight 100. Please update Calendar heading to font weight 300 to match other interior heros.

**Current Calendar Hero setting:**
.events-calendar-header .events-calendar-heading {
    text-align: center;
    _font-size: 1.563em;_
    color: #fff;
    **font-weight: 100;**
    _margin-bottom: 15px;_
    _line-height: 60px;_
}
_NOTE: font-size, margin-bottom, and line-height are all overwritten by @media screen and (min-width: 62.5em) .events-calendar-header .events-calendar-heading._

![event-hero-heading-current](https://user-images.githubusercontent.com/22547623/27191025-824a6b0a-51c4-11e7-860a-0c64864c7c2d.png)

**Desired Calendar Hero setting:**
.events-calendar-header .events-calendar-heading {
    text-align: center;
    color: #fff;
    **font-weight: 300;**
}

**Comment by mavedisian** [comment]
This is fixed and pushed to production. Thanks for being so thorough with your notes!
