### ISSUE TITLE
Interior Hero text: Change heading styling for Blog pages

### ISSUE THREAD

**Issue by lmajerus** [VitalDevTeam/Center-for-Medical-Simulation#357]
Hi @mavedisian. The hero font weight for the Blog pages (landing and individual post) do not match the same text as other interior page heros. All the full-color and full-image heros have a h1.heading-test font weight of 300 while the Blog headings are font weight 100. Please update Blog heading to font weight 300 to match other interior heros.

**Current Blog Hero setting:**
.blog-header .blog-heading {
    text-align: center;
    font-size: 1.375em;
    color: #fff;
    font-weight: 100;
    padding: 20px;
}
_NOTE: font-size is overwritten by @media screen and (min-width: 40em) .blog-header .blog-heading._
![blog-landing-header-current](https://user-images.githubusercontent.com/22547623/27206919-a02148c6-5208-11e7-8043-32f65f1b8032.png)
![css-hero-blog-header-current](https://user-images.githubusercontent.com/22547623/27206923-ac73bd8e-5208-11e7-876c-4add93bbbf21.png)

**Desired Blog Hero setting:**
.blog-header .blog-heading {
    text-align: center;
    color: #fff;
    **font-weight: 300;**
    padding: 20px;
}

**Comment by mavedisian** [comment]
This is fixed and pushed to production.
