### ISSUE TITLE
Course: Multi-day events appear as single day events in Course Offerings table

### ISSUE THREAD

**Issue by lmajerus** [VitalDevTeam/Center-for-Medical-Simulation#359]
From @lmajerus May 18, 2017 on original issue #338

On Course pages where courses are more than 1 day (e.g. Comprehensive, OR Teams, Advanced Instructor, Simulation as a Teaching Tool, Advanced Debriefing), only the first day of the event appears. This is a mistake. The full range of dates should appear in table.

What currently appears for Comprehensive - just the 1st day:
![screen shot 2017-05-18 at 1 27 57 pm](https://cloud.githubusercontent.com/assets/22547623/26215563/c6c5e928-3bce-11e7-861a-42d3b1d10851.png)

**Comment by lmajerus** [comment]
From @mavedisian May 22, 2017

> On Course pages where courses are more than 1 day (e.g. Comprehensive, OR Teams, Advanced Instructor, Simulation as a Teaching Tool, Advanced Debriefing), only the first day of the event appears. This is a mistake. The full range of dates should appear in table.

This is corrected, please review on staging. 

![2017-06-21 13_18_05-calendar_ multi-day events appear as single day events in month view issue 338](https://user-images.githubusercontent.com/22547623/27397444-50f91ea6-5684-11e7-8d30-cc53259b0459.png)

**Comment by lmajerus** [comment]
From @lmajerus May 26, 2017 on original issue #338 

> On Course pages where courses are more than 1 day (e.g. Comprehensive, OR Teams, Advanced Instructor, Simulation as a Teaching Tool, Advanced Debriefing), only the first day of the event appears. This is a mistake. The full range of dates should appear in table.
> This is corrected, please review on staging.
>
This is close but not quite as desired. The year needs to appear and if it's a full day event, no need to show start/end times. For events that do have start/end times (e.g. not marked full day but with actual times), those times should appear. We want the date formatted as Day, Month DD, YYYY - Day, Month DD, YYYY like: **Tuesday, May 16, 2017 - Friday, May 19, 2017** or for events with times like Day, Month DD, YYYY @ Time 1 - Time 2 like **Tuesday, May 9, 2017 @ 10:30 am - 2:30 pm**.

![2017-06-21 13_22_10-calendar_ multi-day events appear as single day events in month view issue 338](https://user-images.githubusercontent.com/22547623/27397570-ca352da0-5684-11e7-8793-f284ca574f3b.png)

**Comment by lmajerus** [comment]
From @mavedisian May 28, 2017 on original issue #338

Hey @lmajerus I've reviewed your requests and believe I have addressed them all. Please review again on staging. Thanks!

![2017-06-21 13_24_50-calendar_ multi-day events appear as single day events in month view issue 338](https://user-images.githubusercontent.com/22547623/27397700-351d7546-5685-11e7-894b-c86865928c0f.png)

**Comment by lmajerus** [comment]
From @lmajerus June 5, 2017 on original issue #338

Course Offerings Table - on individual Course pages
The year needs to appear along with the month and date - only the day name, month, and date currently appear. If it's a full day event, no need to show start/end times. For events that do have start/end times (e.g. not marked full day but with actual times), those times should appear. We want the date formatted as Day, Month DD, YYYY - Day, Month DD, YYYY like: Tuesday, May 16, 2017 - Friday, May 19, 2017 or for events with times like Day, Month DD, YYYY @ Time 1 - Time 2 like Tuesday, May 9, 2017 @ 10:30 am - 2:30 pm.

Comprehensive course page example showing dates with no year:
2017-06-05 11_47_35-comprehensive instructor workshop _ center for medical simulation

![2017-06-21 13_30_01-calendar_ multi-day events appear as single day events in month view issue 338](https://user-images.githubusercontent.com/22547623/27398020-606721ce-5686-11e7-809d-b5a7e80fca24.png)

**Comment by lmajerus** [comment]
From @mavedisian June 14, 2017 on original issue #338

Hi @lmajerus, above changes were pushed live....

![2017-06-21 13_35_43-calendar_ multi-day events appear as single day events in month view issue 338](https://user-images.githubusercontent.com/22547623/27398489-e3b9ce54-5687-11e7-9a76-266d15c45eef.png)

**Comment by lmajerus** [comment]
Edited from @lmajerus June 15, 2017 on original issue #338

Hi @mavedisian. It looks like some of the formatting & styling on staging moved over to production but others have not. Here are examples that did not seem to move to production yet: 

**Course Offerings table on Course pages (on production):**
The year needs to appear along with the month and date - only the day name, month, and date currently appear. This is fixed on staging (see below).
https://harvardmedsim.org/course/gateway-debriefing-skills-workshop/#course-offerings
![gateway-course-offerings-production](https://user-images.githubusercontent.com/22547623/27189150-7a7f85dc-51be-11e7-9f5b-b19166182db7.png)

**Course Offerings table on Course pages (on staging):**
http://harvardmedsim.staging.wpengine.com/course/gateway-debriefing-skills-workshop/#course-offerings
![gateway-course-offerings-staging](https://user-images.githubusercontent.com/22547623/27189165-849231e6-51be-11e7-9389-8f2e4ad13a11.png)

**Comment by lmajerus** [comment]
From @mavedisian June 20, 2017 on original issue #338

Hi @lmajerus, just wanted to say thanks for bearing with me. There was a lot of information in this thread, so it took some time to completely understand some of the issues. Let's please try to keep issues separate in the future (Course type table issues vs. calendar issues) as it will help prevent long threads like this.

> Course Offerings table on Course pages (on production):
> The year needs to appear along with the month and date - only the day name, month, and date currently appear. This is fixed on staging (see below).

This is done, pushed to production. 

![2017-06-21 14_01_06-calendar_ multi-day events appear as single day events in month view issue 338](https://user-images.githubusercontent.com/22547623/27399400-a6bb1af0-568a-11e7-8062-a7299835987b.png)

**Comment by lmajerus** [comment]
Hi @mavedisian, I've separated out all those issues that were originally tied to #338 into their own tickets. The Course Offerings table on production is almost ready. Here is 1 outstanding issue:

The year needs to appear along with the month and date - only the day name, month, and date currently appear.

**Single Day event:** Day of Week, Month dd, yyyy
**Multi-Day event:** Day of Week, Month dd, yyyy - Day of Week, Month dd, yyyy 
If it's a full day event, no need to show start/end times. 

Here's the current production Course Offerings table examples:
**For Comprehensive Course**
https://harvardmedsim.org/course/comprehensive-instructor-workshop/#course-offerings
![2017-06-21 14_14_38-comprehensive instructor workshop _ center for medical simulation](https://user-images.githubusercontent.com/22547623/27400000-bc261d2a-568c-11e7-8e87-e5b0d84fd1ed.png)

**For MOCA Course**
![image](https://user-images.githubusercontent.com/22547623/27400049-dfe8d158-568c-11e7-9a24-29c1094b413b.png)

**Comment by lmajerus** [comment]
Hi @mavedisian, Here is another outstanding Course Offerings table issue:

**Event with Time:** Day of Week, Month dd, yyyy
For events that do have start/end times (e.g. not marked full day but with actual times), those times should appear. We want the date formatted as Day, Month DD, YYYY - Day, Month DD, YYYY like: Tuesday, May 16, 2017 - Friday, May 19, 2017 or for events with times like Day, Month DD, YYYY @ Time 1 - Time 2 like Tuesday, May 9, 2017 @ 10:30 am - 2:30 pm.

Here's the current staging Course Offerings table example of DASH using a dummy upcoming DASH date:
http://harvardmedsim.staging.wpengine.com/course/debriefing-assessment-for-simulation-in-healthcare-dash-rater-training-workshop/
![2017-06-21 14_25_05-debriefing assessment for simulation in healthcare dash rater training worksho-stag](https://user-images.githubusercontent.com/22547623/27400310-ae9ec944-568d-11e7-80f6-27e7be508b2e.png)

**Comment by mavedisian** [comment]
Hi @lmajerus, I appreciate you separating out concerns! Years have been added to single and multiday events (as needed), additionally times have been added to single and multiday events (as needed). Work was pushed to production after testing.

**Comment by lmajerus** [comment]
Hi @mavedisian, thanks! 
>The year needs to appear along with the month and date - only the day name, month, and date currently appear.

Yes, I see this issue is fixed on production.

>For events that do have start/end times (e.g. not marked full day but with actual times), those times should appear. 

I see this issue is fixed on production. I'm not seeing the implementation on the staging environment. 

Can you please update staging environment with respect to these two fixes and then ok to close.

**Comment by mavedisian** [comment]
Hi @lmajerus this has been pushed to staging as well.
