### ISSUE TITLE
Calendar: No CTA buttons in Day View 

### ISSUE THREAD

**Issue by lmajerus** [VitalDevTeam/Center-for-Medical-Simulation#363]
In List View, events have two CTA buttons at the end of the excerpt: View Event and appropriate CTA depending on Apply Now field (Apply Now / Learn More / Email for Info).

In Day View, there is only a link (not a CTA button) for "Find out more".

Please revise Day View to match the CTA buttons as seen in List View.

**Example Day View on production site:**
![2017-06-21 14_32_57-day-view-production](https://user-images.githubusercontent.com/22547623/27400790-385e392a-568f-11e7-91a7-2f021a36c747.png)

**Example List View on production site:**
![image](https://user-images.githubusercontent.com/22547623/27400763-28ea53e8-568f-11e7-95b5-982f5cb3daf2.png)

**Comment by mavedisian** [comment]
I think this is changed now? I must have addressed this but never commented in this space. Can you confirm? @lmajerus

**Comment by lmajerus** [comment]
Hi @mavedisian, no, I'm still only seeing the CTA button for Apply Now/Email/Learn More. What would have been the button for "View Event" comes through as a link: **Find out more »**. Can you turn that link into a button with the text "View Event"?

![image](https://user-images.githubusercontent.com/22547623/28085753-aebff02a-664a-11e7-96c9-591aa7640979.png)

**Comment by mavedisian** [comment]
Hi @lmajerus, this has been hotfixed and moved to production. Can you test and let me know if it looks good? Thanks!

**Comment by lmajerus** [comment]
Hi @mavedisian, yay! This issue is now resolved 👍
