### ISSUE TITLE
Calendar: Event category missing in Day View

### ISSUE THREAD

**Issue by lmajerus** [VitalDevTeam/Center-for-Medical-Simulation#364]
In List View, the category of an event proceeds the title and details of the event. In Day View, the category is missing entirely.

Please revise Day View to include the category as seen in List View.

**Example Day View on production site:**
![2017-06-21 14_32_57-day-view-production](https://user-images.githubusercontent.com/22547623/27400790-385e392a-568f-11e7-91a7-2f021a36c747.png)

**Example List View on production site:**
![image](https://user-images.githubusercontent.com/22547623/27400763-28ea53e8-568f-11e7-95b5-982f5cb3daf2.png)

**Comment by mavedisian** [comment]
This was added. @lmajerus

**Comment by lmajerus** [comment]
Looks great @mavedisian
