### ISSUE TITLE
Course: Email option not appearing as CTA on Course Offerings table

### ISSUE THREAD

**Issue by lmajerus** [VitalDevTeam/Center-for-Medical-Simulation#365]
When creating an event, I have the option of selecting Internal/External/Email for the Apply Now Link Type field. The selected option appears as a CTA button on the Event Details page and List View calendar pages. I've entered issue#363 to have that CTA button added to Day View page. 

In Course Offerings table on Course pages, only the Internal & External Apply Now type CTA buttons appear in the right most column (there's no header for that column). 

Please correct so that the Email Apply Now type CTA button appears. Email CTA button text should be "Email for Info" to match the CTA buttons on all other pages (i.e. Event Details, List and Day view).

Example production Course Offerings tables where this problem occurs:
Gateway: https://harvardmedsim.org/course/gateway-debriefing-skills-workshop/#course-offerings
![image](https://user-images.githubusercontent.com/22547623/27401314-df22fbd2-5690-11e7-891c-45a0f2a20766.png)

Simulation as a Teaching Tool: https://harvardmedsim.org/course/simulation-as-a-teaching-tool/#course-offerings
![image](https://user-images.githubusercontent.com/22547623/27401264-b992cf14-5690-11e7-8991-b3ce0caa245e.png)

**Comment by mavedisian** [comment]
Hi @lmajerus, a hotfix was pushed to production. Please test. Thank you!

**Comment by lmajerus** [comment]
Thanks @mavedisian , this issue is resolved on production.
