### ISSUE TITLE
Gravity Forms Integration with PayPal: Are we compliant with new MasterCard rules?

### ISSUE THREAD

**Issue by lmajerus** [VitalDevTeam/Center-for-Medical-Simulation#366]
We received a notification from PayPal alerting us to MasterCard's Bank Identification Number changes. PayPal itself is compliant but they were alerting us to ensure we check that we're in compliance with our integration method.

I tried to figure out if we were compliant by using our Donate form and entering some make-believe card number that started with the new BIN range "222100". The form did recognize that it was a MasterCard but I'm not sure how exactly to test more than that because it's not a real number!

Do you know if we are compliant with these new MasterCard BIN numbers?

[email-PayPal-MasterCard-change-Jun-21-2017.pdf](https://github.com/VitalDevTeam/Center-for-Medical-Simulation/files/1092800/email-PayPal-MasterCard-change-Jun-21-2017.pdf)

**Comment by mavedisian** [comment]
The form is using a plugin to verify credit card numbers and looks like it's working to account for new bins. PayPal has updated their systems to account for new bins, so we're covered.
