### ISSUE TITLE
Calendar: Event Details not showing Notes content

### ISSUE THREAD

**Issue by lmajerus** [VitalDevTeam/Center-for-Medical-Simulation#367]
When creating an Event, there is a section called Post Event with 2 areas for content: Notes and Pricing Info boxes. The Pricing Info boxes appear correctly on the Event Details page. The Notes do not appear anywhere on the Event Details page - they only appear on a Course page (in the Course Offerings Table) and in the Course Application (Apply Now) form.

Please have the content from the Notes field appear on the Event Details page. If we didn't already design where this should go, I'm thinking the content should be displayed under the Event Description area under a new heading "Notes" and above the buttons to add to Google Calendar and iCal Export.

Back-end example for Pain CRM Workshop Aug 30, 2017 showing Notes field:
![event-add-notes-back-end](https://user-images.githubusercontent.com/22547623/27484221-6a442ec8-57f6-11e7-8070-c84f2a676312.png)

Corresponding front-end Event Details for Pain CRM Workshop Aug 30, 2017 not showing Notes field:
![event-notes-from-backend-not-on-event-details](https://user-images.githubusercontent.com/22547623/27483542-d4d77cfc-57f3-11e7-8503-fd4d1870d38e.png)

Placement suggestion (if not already designed) of new Notes header and Notes field contents. Formatting of Notes header should match Details & Venue in size, color, and font weight. Formatting of Notes field contents should match Event Description styling.
![event-add-notes-from-backend-on-event-details](https://user-images.githubusercontent.com/22547623/27484188-44636304-57f6-11e7-8e2f-3ec47fc29533.png)

**Comment by mavedisian** [comment]
Notes will now show on single event pages.
They will only show if notes are provided.
Style matches the lower h3 tags as requested. 
Changes pushed to production.

**Comment by lmajerus** [comment]
This looks great @mavedisian!
