### ISSUE TITLE
Interior Hero text: Change heading styling for Resource pages

### ISSUE THREAD

**Issue by lmajerus** [VitalDevTeam/Center-for-Medical-Simulation#368]
The hero font weight for the Resource pages (landing and individual post) do not match the same text as other interior page heros. All the full-color and full-image heros have a h1.heading-test font weight of 300 while the Resource headings are font weight 100. Please update Resource heading to font weight 300 to match other interior heros.

**Current Resource Hero setting:**
.resources-header .resources-heading {
    text-align: center;
    font-size: 1.875em;
    color: #fff;
    font-weight: 100;
    margin-bottom: 15px;
}

_NOTE: font-size and margin-bottom are overwritten by @media screen and (min-width: 62.5em)
.resources-header .resources-heading_
![resources hero](https://user-images.githubusercontent.com/22547623/27488104-df3d3fd2-5803-11e7-8053-716efdcfdeb7.png)
![resources-heading-css-prod](https://user-images.githubusercontent.com/22547623/27488115-e1e97606-5803-11e7-9a64-f8e5317da282.png)

**Desired Resource Hero setting:**
.resources-header .resources-heading {
    text-align: center;
    color: #fff;
    **font-weight: 300;**
}

**Comment by mavedisian** [comment]
This has been corrected and added to production.
