### ISSUE TITLE
SFTP access to Live & Staging environments

### ISSUE THREAD

**Issue by lmajerus** [VitalDevTeam/Center-for-Medical-Simulation#369]
I don't have any info on how to SFTP for the new site. I found the place in the WP Engine area that gives the SFTP info. 
>Your SFTP access (not FTP!) is at hostname harvardmedsim.wpengine.com or IP at 104.196.49.155 on port 2222. You will need to create a Username and Password in order to gain access. This can be [created here](https://my.wpengine.com/).

However, when I click on the "created here" link, I'm prompted to enter my login info to WPEngine or sign up for a new account. I've poked around and I think you guys need to add me as a user to WPEngine. Here's instructions for adding specifically SFTP access: https://wpengine.com/support/how-do-i-add-new-sftp-accounts/. I'd like access to both Live & Staging (the later in case I do need to test in staging).

**Comment by mavedisian** [comment]
Sent you an email.
