### ISSUE TITLE
URL redirect for 2 PDF files: HCA Graphic Gameplan and HCA Graphic Gameplan Facilitators Guide

### ISSUE THREAD

**Issue by lmajerus** [VitalDevTeam/Center-for-Medical-Simulation#370]
Our collaboration between Healthcare Adventures and the National Patient Safety Foundation created this “sell page:” http://npsf.site-ym.com/blogpost/1158873/229564/A-Gameplan-for-Engaging-Leaders-Staff-in-Quality-and-Safety

That article links to the free download for the HCA Graphic Gameplan and HCA Graphic Gameplan Facilitators Guide. The links used in that article point to the old site and the currently set redirects throw a 404 error. 

The redirect root both files are currently pointing to is http://harvardmedsim.org/wp-content/uploads/2017/01/pdfs/. If you remove the directory **/pdfs/** from the redirect, that would lead to the correct files.

Please add/correct redirects:

OLD LINK: https://harvardmedsim.org/_media/pdfs/HCA-Graphic-Gameplan-FacilitatorsGuide.pdf
NEW LINK: https://harvardmedsim.org/wp-content/uploads/2017/01/HCA-Graphic-Gameplan-FacilitatorsGuide.pdf

OLD LINK: https://harvardmedsim.org/_media/pdfs/HCA-Graphic-Gameplan.pdf
NEW LINK: https://harvardmedsim.org/wp-content/uploads/2017/01/HCA-Graphic-Gameplan.pdf

**Comment by mavedisian** [comment]
Hi @lmajerus, these redirects are in place on production.
