### ISSUE TITLE
URL Redirect: \course and \course-type to \training

### ISSUE THREAD

**Issue by lmajerus** [VitalDevTeam/Center-for-Medical-Simulation#371]
All our courses have a root https://harvardmedsim.org/course/ followed by the slug for the specific course. Similarly the course types have a root https://harvardmedsim.org/course-type/ followed by the slug.

If a user tries to go to the root directly to see other courses or course types, they receive a 404 error. I'd like to correct that to put them back into the funnel.

I'd like to redirect 
FROM: https://harvardmedsim.org/course/ 
TO: https://harvardmedsim.org/training/

FROM: https://harvardmedsim.org/course-type/
TO: https://harvardmedsim.org/training/

**Comment by mavedisian** [comment]
Hi @lmajerus, these redirects are in place on production.

**Comment by lmajerus** [comment]
Hi @mavedisian, I just went to https://harvardmedsim.org/course/ and https://harvardmedsim.org/course-type/. Both are still providing a 404 error.

**Comment by mavedisian** [comment]
@lmajerus Strange, sorry about that... I reviewed our redirects and added a couple that seemed to be missing. Can you test again please? Thank you!

**Comment by lmajerus** [comment]
Thanks @mavedisian, this issue is now resolved - the redirects work 👍
