### ISSUE TITLE
CMS Team: heading anchor links not clickable

### ISSUE THREAD

**Issue by lmajerus** [VitalDevTeam/Center-for-Medical-Simulation#372]
The top of the CMS Team page body has anchor links to each heading on the page: Leadership, Principal Faculty, Operations Team, Adjunct Faculty. These anchor headings used to be clickable and would shoot you down to that heading further down on the page. In Chrome, those links are no longer clickable (see image below). Inspection of code indicates those titles are all still links. Please restore clickability of these heading anchor links.
![image](https://user-images.githubusercontent.com/22547623/28325145-1a1d4e98-6bab-11e7-881a-8f51802e8c4d.png)

**Comment by mavedisian** [comment]
Hi @lmajerus, this issue was hotfixed and pushed to production.

**Comment by lmajerus** [comment]
Thanks @mavedisian, this issue is fixed.
